name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Ruby (для Fastlane или CocoaPods, если нужно)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install dependencies (если есть)
        run: |
          gem install bundler
          bundle install
          # или просто: pod install (если используешь CocoaPods)

      - name: Build app
        run: |
          xcodebuild clean build \
          -project YourApp.xcodeproj \
          -scheme YourApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'

      - name: Run tests
        run: |
          xcodebuild test \
          -project YourApp.xcodeproj \
          -scheme YourApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'

